openapi: 3.0.0
info:
  title: Poutine API
  version: 1.0.0
paths:
  /cook-poutine/{potatoSize}/{boilTime}/{oilType}/{temperature}:
    get:
      summary: Cook poutine
      parameters:
        - name: potatoSize
          in: path
          required: true
          schema:
            type: integer
          description: Size (inch per inch) of the potato cubes
        - name: boilTime
          in: path
          required: true
          schema:
            type: integer
          description: Time (in minutes) to boil the potatoes
        - name: oilType
          in: path
          required: true
          schema:
            type: string
          description: Type of oil to use
        - name: temperature
          in: path
          required: true
          schema:
            type: integer
          description: Specific temperature (in celsius) to keep the things warm
      responses:
        '200':
          description: Poutine cooked successfully
        '500':
          description: Error occurred

  /send-poutine/{drunkIsDetected}:
    get:
      summary: Send poutine
      parameters:
        - name: drunkIsDetected
          in: path
          required: true
          schema:
            type: boolean
          description: Send poutine if drunk clients are detected
      responses:
        '200':
          description: Poutine sent successfully
        '500':
          description: Error occurred
